MvcProjectCamp/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
	public class AuthorizationController : Controller
	{
		AdminManager adminManager = new AdminManager(new EfAdminDal());
		public ActionResult Index()
		{
			var adminValues = adminManager.GetAdminList();
			return View(adminValues);
		}

		[HttpGet]
		public ActionResult AddAdmin()
		{
			return View();
		}
		[HttpPost]
		public ActionResult AddAdmin(Admin admin)
		{
			adminManager.AdminAdd(admin);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult EditAdmin(int id)
		{
			var adminValues = adminManager.GetByIdAdmin(id);
			var adminInfo=adminValues.AdminRole.ToString();
			if (adminInfo == "A")
			{
				return View(adminValues);
			}

            else
            {
				return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden, "Yetkiniz yok.");
			}
        }

		[HttpPost]
		public ActionResult EditAdmin(Admin admin)
		{
			adminManager.AdminUpdate(admin);
			return RedirectToAction("Index");
		}

		public ActionResult DeleteAdmin(int id)
		{
			var result = adminManager.GetByIdAdmin(id);
			adminManager.AdminDelete(result);
			return RedirectToAction("Index");
		}
	}
}

MvcProjectCamp/Views/Authorization/AddAdmin.cshtml
﻿﻿@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Admin Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifreyi Giriniz")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Rolü Seçiniz")
        @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>

}

MvcProjectCamp/Views/Authorization/EditAdmin.cshtml
﻿﻿@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
    <div class="form.group">
        @Html.HiddenFor(x => x.AdminId, new { @class = "form-control" })
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Rol")
        @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>

}

MvcProjectCamp/Views/Authorization/Index.cshtml
﻿﻿@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Mail</th>
        <th>Yetki</th>
        <th>Durum</th>
        <th>Yetki Al</th>
        <th>Yetki Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminId</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="/Authorization/DeleteAdmin/@item.AdminId" class="btn btn-danger">Yetki Al</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminId" class="btn btn-warning">Yetki Değiştir</a></td>
        </tr>
    }
</table>
<a href="/Authorization/AddAdmin" class="btn btn-info">Yeni Admin Tanımla</a>