MvcProjectCamp/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
	public class MessageController : Controller
	{
		MessageManager manager = new MessageManager(new EfMessageDal());
		MessageValidator validationRules = new MessageValidator();
		[Authorize]
		public ActionResult Inbox(string p)
		{
			var messageList = manager.GetListInbox(p);
			ViewBag.unreadMessage=messageList.Where(x=>x.IsRead==false).Count();
			return View(messageList);
		}

		public ActionResult Sendbox(string p)
		{
			var messageList = manager.GetListSendbox(p);
			return View(messageList);
		}
		public ActionResult GetInboxMessageDetails(int id)
		{
			// Mesajı veritabanından al
			var values = manager.GetById(id);

			// Eğer mesaj okunmamışsa, okundu olarak işaretle
			if (values != null && !values.IsRead)
			{
				values.IsRead = true;  // Mesaj okundu olarak işaretlendi
				manager.MessageUpdate(values);  // Güncellenmiş mesajı kaydet
			}

			return View(values);  // Mesajın detaylarını görüntüle
		}

		public ActionResult GetSendboxMessageDetails(int id)
		{
			var values = manager.GetById(id);
			return View(values);
		}

		[HttpGet]
		[ValidateInput(false)]
		public ActionResult NewMessage()
		{
			return View();
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult NewMessage(Message message)
		{
			ValidationResult results = validationRules.Validate(message);
			if (results.IsValid)
			{
				message.MessageDate=DateTime.Parse(DateTime.Now.ToShortDateString());
				manager.MessageAdd(message);
				return RedirectToAction("Sendbox");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();		
		}


		[HttpPost]
		public ActionResult DeleteMessages(List<int> messageIds,string redirectView)
		{
			manager.DeleteMessages(messageIds);
			// Silme işleminden sonra hangi sayfaya dönüleceğine karar ver
			if (redirectView == "Inbox")
			{
				return RedirectToAction("Inbox");
			}
			else if (redirectView == "Sendbox")
			{
				return RedirectToAction("Sendbox");
			}
			else
			{
				return RedirectToAction("TrashMessages"); // Varsayılan olarak Çöp Kutusuna git
			}
		}

		public ActionResult TrashMessages()
		{
			string p = (string)Session["WriterMail"];
			var values = manager.GetTrashMessages(p).ToList();
			return View(values);
		}

		[HttpGet]
		public ActionResult DraftList()
		{
			string p = (string)Session["WriterMail"];
			var draftMessages=manager.GetDraftMessages(p);
			return View(draftMessages);
		}
		[ValidateInput(false)]
		public ActionResult DraftDetail(int id)
		{
			var values=manager.GetById(id);
			return View(values);
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult SaveDraft(Message message)
		{
			message.MessageDate = DateTime.Now;
			message.IsDraft = true;
			manager.MessageAdd(message);
			return RedirectToAction("DraftList");
			//return Json(new { success = true });
		}

		public ActionResult ToggleReadStatus(int id)
		{
			manager.ToggleReadStatus(id);  // Mesajın okundu/okunmadı durumunu değiştir

			return RedirectToAction("Inbox");  // Inbox sayfasına yönlendir
		}
	}
}

MvcProjectCamp/Controllers/WriterPanelMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class WriterPanelMessageController : Controller
    {
		MessageManager manager = new MessageManager(new EfMessageDal());
		MessageValidator validationRules = new MessageValidator();

		public ActionResult Inbox()
		{
			string p = (string)Session["WriterMail"];
			var messageList = manager.GetListInbox(p);
			ViewBag.unreadMessage = messageList.Where(x => x.IsRead == false).Count();
			return View(messageList);
		}

		public PartialViewResult MessageMenuPartial()
		{
			string p = (string)Session["WriterMail"];
			ViewBag.inboxMessageCount = manager.GetListInbox(p).Count;
			ViewBag.sendMessageCount = manager.GetListSendbox(p).Count;
			ViewBag.trashMessages = manager.GetTrashMessages(p).Count();
			ViewBag.draftMessageCount = manager.GetDraftMessages(p).Count();
			return PartialView();
		}

		public ActionResult Sendbox()
		{
			string p = (string)Session["WriterMail"];
			var messageList = manager.GetListSendbox(p);
			return View(messageList);
		}

		public ActionResult GetInboxMessageDetails(int id)
		{
			// Mesajı veritabanından al
			var values = manager.GetById(id);

			// Eğer mesaj okunmamışsa, okundu olarak işaretle
			if (values != null && !values.IsRead)
			{
				values.IsRead = true;  // Mesaj okundu olarak işaretlendi
				manager.MessageUpdate(values);  // Güncellenmiş mesajı kaydet
			}

			return View(values);  // Mesajın detaylarını görüntüle
		}

		public ActionResult GetSendboxMessageDetails(int id)
		{
			var values = manager.GetById(id);
			return View(values);
		}

		[HttpGet]
		[ValidateInput(false)]
		public ActionResult NewMessage()
		{
			return View();
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult NewMessage(Message message)
		{
			string p = (string)Session["WriterMail"];
			ValidationResult results = validationRules.Validate(message);
			if (results.IsValid)
			{
				message.SenderMail = p;
				message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
				manager.MessageAdd(message);
				return RedirectToAction("Sendbox");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
		}

		[HttpPost]
		public ActionResult DeleteMessages(List<int> messageIds, string redirectView)
		{
			string p = (string)Session["WriterMail"];

			manager.DeleteMessages(messageIds);
			// Silme işleminden sonra hangi sayfaya dönüleceğine karar ver
			if (redirectView == "Inbox")
			{
				return RedirectToAction("Inbox");
			}
			else if (redirectView == "Sendbox")
			{
				return RedirectToAction("Sendbox");
			}
			else
			{
				return RedirectToAction("TrashMessages"); // Varsayılan olarak Çöp Kutusuna git
			}
		}

		public ActionResult TrashMessages()
		{
			string p = (string)Session["WriterMail"];
			var values = manager.GetTrashMessages(p).ToList();
			return View(values);
		}

		[HttpGet]
		public ActionResult DraftList()
		{
			string p = (string)Session["WriterMail"];
			var draftMessages = manager.GetDraftMessages(p);
			return View(draftMessages);
		}
		[ValidateInput(false)]
		public ActionResult DraftDetail(int id)
		{
			var values = manager.GetById(id);
			return View(values);
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult SaveDraft(Message message)
		{
			string p = (string)Session["WriterMail"];
			message.SenderMail = p;
			message.MessageDate = DateTime.Now;
			message.IsDraft = true;
			manager.MessageAdd(message);
			return RedirectToAction("DraftList");
			//return Json(new { success = true });
		}

		public ActionResult ToggleReadStatus(int id)
		{
			manager.ToggleReadStatus(id);  // Mesajın okundu/okunmadı durumunu değiştir

			return RedirectToAction("Inbox");  // Inbox sayfasına yönlendir
		}
	}
}

MvcProjectCamp/Views/WriterPanelMessage/DraftDetail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "DraftDetail";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            @Html.Action("MessageMenuPartial", "WriterPanelMessage")
            <!-- /.col -->
            <div class="col-md-9">
                @using (Html.BeginForm("NewMessage", "WriterPanelMessage", FormMethod.Post))
                {
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Taslak Mesaj</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="form-group">
                                @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control", placeholder = "Kime" })
                                @Html.ValidationMessageFor(x => x.ReceiverMail)
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", placeholder = "Konu" })
                                @Html.ValidationMessageFor(x => x.Subject)
                            </div>
                            <div class="form-group">
                                <textarea id="compose-textarea" class="form-control" name="MessageContent" style="height: 300px">
                            @*@Html.TextAreaFor(x=>x.MessageContent, new { @class = "form-control"})*@
@Html.Raw(Model.MessageContent) <!-- HTML içeriği Summernote'a yüklenir -->
                    </textarea>
                            </div>
                            <div class="form-group">
                                <div class="btn btn-default btn-file">
                                    <i class="fas fa-paperclip"></i> Dosya Ekle
                                    <input type="file" name="attachment">
                                </div>
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="float-right">
                                @*<button type="submit" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>*@
                                <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                            </div>
                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                }
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
</body>
</html>

@* Biçimlenmiş metini taslak olarak göstermek için*@
<script>
    $(document).ready(function () {
        $('#compose-textarea').summernote({
            height: 300, // Editör yüksekliği
            placeholder: 'Mesajınızı buraya yazın...',
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });

        // Daha önce kaydedilmiş içeriği Summernote'a yükleyin
        var kaydedilmisIcerik = '@Html.Raw(Model.MessageContent)';
        $('#compose-textarea').summernote('code', kaydedilmisIcerik);
    });
</script>

MvcProjectCamp/Views/WriterPanelMessage/DraftList.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "DraftList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageMenuPartial", "WriterPanelMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Taslak Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <form method="post" action="/WriterPanelMessage/DraftDetail">
                            <input type="hidden" name="redirectView" value="Inbox" />
                            <div class="mailbox-controls">
                                <!-- Check all button -->
                                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>

                                <div class="btn-group">
                                    <button href="#" type="submit" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                                </div>
                                <!-- /.btn-group -->
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                                <div class="float-right">
                                    1-50/200
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                    </div>
                                    <!-- /.btn-group -->
                                </div>
                                <!-- /.float-right -->
                            </div>
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="icheck-primary">
                                                        <input type="checkbox" name="messageIds" value="@item.MessageId" id="MessageId">
                                                        <label for="MessageId"></label>
                                                    </div>
                                                </td>
                                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <td class="mailbox-name"><a href="/WriterPanelMessage/DraftDetail/@item.MessageId">@item.SenderMail</a></td>
                                                <td class="mailbox-subject">
                                                    <b>@item.Subject</b> - @item.MessageContent.Substring(0, 10)...
                                                </td>
                                                <td class="mailbox-attachment"></td>
                                                <td class="mailbox-date">@Convert.ToDateTime(item.MessageDate).ToString("dd/MMM/yyyy")</td>
                                            </tr>
                                        }

                                    </tbody>

                                </table>

                                <!-- /.table -->
                            </div>
                        </form>
                        <!-- /.mail-box-messages -->
                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer p-0">

                    </div>
                </div>

                <!-- /.card -->
            </div>

            <!-- /.col -->
        </div>

        <!-- /.row -->
    </section>

</body>

</html>

MvcProjectCamp/Views/WriterPanelMessage/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageMenuPartial", "WriterPanelMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <form method="post" action="/Message/DeleteMessages">
                            <input type="hidden" name="redirectView" value="Inbox" />
                            <div class="mailbox-controls">
                                <!-- Check all button -->
                                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>

                                <div class="btn-group">
                                    <button href="#" type="submit" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                </div>
                                <!-- /.btn-group -->
                                <label style="color:lightcoral;margin-left:15px" class="btn btn-outline-light">Okunmamış Mesaj Sayısı: @ViewBag.unreadMessage</label>
                                <div class="float-right">
                                    1-50/200
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                    </div>
                                    <!-- /.btn-group -->
                                </div>
                                <!-- /.float-right -->
                            </div>
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="icheck-primary">
                                                        <input type="checkbox" name="messageIds" value="@item.MessageId" id="MessageId">
                                                        <label for="MessageId"></label>
                                                    </div>
                                                </td>
                                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <td class="mailbox-name"><a href="/Message/GetInboxMessageDetails/@item.MessageId">@item.SenderMail</a></td>
                                                <td class="mailbox-subject">
                                                    <b>@item.Subject</b> - @item.MessageContent.Substring(0, 10)...
                                                </td>
                                                <td class="mailbox-attachment">
                                                    <!-- Okundu durumu kontrolü ve zarf ikonunun değişimi -->
                                                    <a href="@Url.Action("ToggleReadStatus", "Message", new { id = item.MessageId })">
                                                        @if (item.IsRead)
                                                        {
                                                            <i class="fas fa-envelope-open text-success"></i> <!-- Okunmuş, açık zarf -->
                                                        }
                                                        else
                                                        {
                                                            <i class="fas fa-envelope text-danger"></i> <!-- Okunmamış, kapalı zarf -->
                                                        }
                                                    </a>
                                                </td>
                                                <td class="mailbox-date">@Convert.ToDateTime(item.MessageDate).ToString("dd/MMM/yyyy")</td>
                                            </tr>
                                        }

                                    </tbody>

                                </table>

                                <!-- /.table -->
                            </div>
                        </form>
                        <!-- /.mail-box-messages -->
                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer p-0">

                    </div>
                </div>

                <!-- /.card -->
            </div>

            <!-- /.col -->
        </div>

        <!-- /.row -->
    </section>

</body>

</html>

MvcProjectCamp/Views/WriterPanelMessage/NewMessage.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            @Html.Action("MessageMenuPartial", "WriterPanelMessage")
            <!-- /.col -->
            <div class="col-md-9">
                @using (Html.BeginForm("NewMessage", "WriterPanelMessage", FormMethod.Post))
                {
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Yeni Mesaj</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="form-group">
                                @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control", placeholder = "Kime" })
                                @Html.ValidationMessageFor(x => x.ReceiverMail)
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", placeholder = "Konu" })
                                @Html.ValidationMessageFor(x => x.Subject)
                            </div>
                            <div class="form-group">
                                <textarea id="compose-textarea" class="form-control" name="MessageContent" style="height: 300px">
                            
                    </textarea>
                            </div>
                            <div class="form-group">
                                <div class="btn btn-default btn-file">
                                    <i class="fas fa-paperclip"></i> Dosya Ekle
                                    <input type="file" name="attachment">
                                </div>
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">

                            <div class="float-right ml-2">
                                <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                            </div>


                            <div class="float-right">
                                <button type="submit" formaction="@Url.Action("SaveDraft", "WriterPanelMessage")" formmethod="post" class="btn btn-default">
                                    <i class="fas fa-pencil-alt"></i> Taslaklara Kaydet
                                </button>
                            </div>


                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                }
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
</body>
</html>

@* Biçimlenmiş metini taslak olarak kaydetmek için*@
<script>
    $(document).ready(function () {
        $('#compose-textarea').summernote({
            height: 300, // Editör yüksekliği
            placeholder: 'Mesajınızı buraya yazın...',
            toolbar: [
                // İstediğiniz toolbar seçeneklerini belirleyin
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    });


    $('#saveDraftButton').on('click', function (e) {
        e.preventDefault(); // Sayfanın yenilenmesini önler
        var mesajIcerigi = $('#compose-textarea').summernote('code'); // HTML içeriği al

        // AJAX ile sunucuya kaydetme isteği gönderin
        $.ajax({
            type: 'POST',
            url: '@Url.Action("SaveDraft", "Message")',
            data: {
                ReceiverMail: $('#ReceiverMail').val(),
                Subject: $('#Subject').val(),
                MessageContent: mesajIcerigi
            },
            success: function (response) {
                alert("Mesaj taslak olarak kaydedildi.");
            }
        });
    });
</script>